// Layout
export const CLOSE_NAVIGATOR = 'CLOSE_NAVIGATOR'
export const TOGGLE_NAVIGATOR = 'TOGGLE_NAVIGATOR'
export const CLOSE_CHOOSER = 'CLOSE_CHOOSER'
export const TOGGLE_CHOOSER = 'TOGGLE_CHOOSER'
